server:
  port: 8081

spring:
  profiles:
    active: dev
  application:
    name: task-manager

  datasource:
    url: jdbc:postgresql://localhost:5432/taskmanager
    username: postgres
    password: example

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.nowakpawel: INFO
    org.springframework: INFO