name: Main Build & Artifact

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y build-essential
      - run: gcc -o app ./legacy-experiments/main.c
      - run: ./legacy-experiments/test.sh
      - name: Upload compiled artifact
        uses: actions/upload-artifact@v4
        with:
          name: c-app
          path: app
